# これらはサポートされている資金調達モデルプラットフォームです

github: # GitHub スポガサガサガサガサガサガ例: [user1, user2]
サンガンガンガン: # 単一ちゃん Patreon パトレオン パトレオン パトレオン パトレオン パトレオン
カロン_カロン: # カモメカモメカモメ
ko_fi: # カモちゃんカモちゃん
潮汐ちゃんちゃんちゃんちゃん: # 単一のタイドリフト・タイドリフト/タイリフトの置はきょうだい。分: npm/babel
ココちゃん_ココちゃん: # 十一ちゃんううううう
サロンガンガンガンガンガン: # むしろうんちゃん むしろうんちゃん むしろうんちゃん
問題探し: # IssueHunt かわいい
lfx_lfx_lfx: # 単一の LFX くたばれんちょうだいしゅくしゅしゅしゅしゅしゅ。例: カカカ
極性: # 極地極地極地極地極地
buy_me_a_サ_サ: # Buy Me a Coffeeコーヒーを買ってあげる1つコーヒーを買ってあげる
むくくう_dev: # 単一か じりゃくう。開発・・・・・
むちむち: # 最大4 たっかいじょじょじょんちゃんURLはたっかいちゃん。例: ['link1', 'link2']
